# Generated by Django 5.1.6 on 2025-03-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife_sounds', '0003_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownSpecie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=100)),
            ],
        ),
    ]
