# Generated by Django 5.1.1 on 2025-03-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife_sounds', '0004_unknownspecie'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='max_score',
            field=models.IntegerField(default=0, verbose_name='max_score'),
        ),
        migrations.AddField(
            model_name='score',
            name='nb_error',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='nb_scientific',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='nb_vernacular',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(default=0, verbose_name='score'),
        ),
    ]
